#!/bin/bash
# RUN $ sudo bash bash_gulp IN TERMINAL WHEN DEPLOYING FOR DEVELOPMENT.
# REMEMBER TO CHANGE/REMOVE LINKS IN YOUR MAIN HTML PAGE WHERE YOUR MAIN.CSS AND MAIN.JS FILES ARE REFERENCED.

gulp bundle-sass
gulp minify-css
gulp compress-css

gulp bundle-minify-scripts
gulp compress-js

#gulp compress-images
